version: "3.8"

services:
  mysqldb:
    container_name: sern_mysql
    image: mysql:8.0
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_CONTAINER_PORT
    expose:
      - $MYSQLDB_CONTAINER_PORT
    volumes:
      - sern-db:/var/lib/mysql
    networks:
      - server-network

  server:
    container_name: sern_server
    depends_on:
      - mysqldb
    image: tuchan17/sern-boilerplate_server
    restart: always
    env_file: ./.env
    ports:
      - 8080:8080
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_CONTAINER_PORT
    expose:
      - 8080
    networks:
      - server-network
      - web-network

  web:
    container_name: sern_web
    depends_on:
      - server
    restart: always
    image: tuchan17/sern-boilerplate_web
    ports:
      - 5000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web-network

volumes:
  sern-db:

networks:
  server-network:
  web-network:
