version: "3.8"

services:
  mysqldb:
    container_name: sern-boilerplate_mysql
    image: mysql:8.0
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    expose:
      - $MYSQLDB_DOCKER_PORT
    volumes:
      - sern-boilerplate-db:/var/lib/mysql
    networks:
      - server

  server:
    container_name: sern-boilerplate_server
    depends_on:
      - mysqldb
    build: ./server
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    volumes:
      - ./server:/sern-boilerplate-server
      - /sern-boilerplate-server/node_modules
    networks:
      - server
      - web

volumes:
  sern-boilerplate-db:
  sern-boilerplate-server:

networks:
  server:
  web:
