version: "3.8"

services:
  mysqldb:
    container_name: sern_mysql
    image: mysql:8.0
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 9906:3306
    expose:
      - 3306
    volumes:
      - sern-db:/var/lib/mysql
    networks:
      - server-network

  server:
    container_name: sern_server
    depends_on:
      - mysqldb
    build:
      context: ./web
    restart: always
    env_file: ./.env
    ports:
      - 8080:8080
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_CONTAINER_PORT
    volumes:
      - ./server:/sern-server
      - /sern-server/node_modules
    networks:
      - server-network
      - web-network

  web:
    container_name: sern_web
    depends_on:
      - server
    restart: always
    build:
      context: ./web
    ports:
      - 5050:80
    networks:
      - web-network

volumes:
  sern-db:
  sern-server:

networks:
  server-network:
  web-network:
